### ISSUE TITLE
[UI] Create the Footer

### ISSUE THREAD

**Issue by Neha** [RealDevSquad/feature-flag-service#26]
- Copyright
- Developer (Optional)
- Redirect to RDS

**Comment by pallabez** [comment]
Can you give a reference for it?

**Comment by Neha** [comment]
<img width="890" alt="image" src="https://user-images.githubusercontent.com/61655/178148694-741c034d-640d-46ea-a28e-cc7e4ba86606.png">

**Comment by Neha** [comment]
I am working on this
