### ISSUE TITLE
[UI] Sort

### ISSUE THREAD

**Issue by Neha** [RealDevSquad/feature-flag-service#33]
Sorting on Date

**Comment by Tejas-ChandraShekarRaju** [comment]
Let me know if I can pick this up. 
@pallabez

**Comment by pallabez** [comment]
Assigned it to you :+1:

**Comment by Tejas-ChandraShekarRaju** [comment]
@pallabez. 

1.What part of the UI is sort required? 
2. Do we already have some component which lists the data?
Any directions would be great.
Thanks

**Comment by Neha** [comment]
1. What part of the UI is sort required?

We want a feature where the user can sort the Feature flags in their dashboard on the basis of the date - sort on date

2.  Do we already have some component which lists the data?

Please check the pinned Miro board in the channel of the Feature flag

3. Do check PR #52 


Feel free to ask any question

**Comment by Tejas-ChandraShekarRaju** [comment]
@Neha I requested access to the miro board. 

It would be great if you could grant access.

**Comment by Tejas-ChandraShekarRaju** [comment]
Hi @Neha.

Request to review the below PR
https://github.com/Real-Dev-Squad/feature-flag-service/pull/63

Thanks

**Comment by Tejas-ChandraShekarRaju** [comment]
https://github.com/Real-Dev-Squad/feature-flag-service/pull/63

Completed. FYI: This ticket has other changes requested which will be a different PR under a different ticket

**Comment by Tejas-ChandraShekarRaju** [comment]
@pallabez can you close this issue?

**Comment by Tejas-ChandraShekarRaju** [comment]
Completed. Raised other tickets for CSS optimizations, Accessibility.
